/*Buenas RAFA, espero que leas este mini comentario. Tenía algunos errores
de código que he solucionado. No se porqué si pongo 8 equipos del mismo país
y 8 de otro me los empareja mal. Le he dado muchas vueltas al ejercicio, pero
no se cómo solucionarlo. En la condición de emparejar al poner solo que distinguiese
países sí lo hacía bien, pero al mezclar grupo y país algunos partidos los hace mal.
El resto de sorteos eran más faciles y los hace bien. En octavos he intentado
seguir el modelo de la vida real de octavos.

En resumen, por muchas horas que le he dedicado, no he sido capaz de que haga bien lo 
de octavos. Lo he intentado con bucles y el random, y no había manera de hacerlo. Se 
que me queda mas de una semana todavía, pero no tengo ganas de dejarlo para el último 
día. Feliz año y un saludo.
*/

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fco Javier Torrejon Aragon
 */
public class EJ2 extends javax.swing.JFrame {
    public ArrayList<Equipo>bombo;
    public int opcion;
    /**
     * Creates new form EJ2
     */
    public EJ2() {
        
        initComponents();
        this.getContentPane().setBackground(new Color(3, 35, 167));
        this.ventanaConsultaEquiposRegistrados.getContentPane().setBackground(new Color(3, 35, 167));
        this.ventanaEmparejamiento.getContentPane().setBackground(new Color(3, 35, 167));
        this.ventanaRegistro.getContentPane().setBackground(new Color(3, 35, 167));
        this.ventanaTipoSorteo.getContentPane().setBackground(new Color(3, 35, 167));
        bombo=new ArrayList<>();
        opcion=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaTipoSorteo = new javax.swing.JDialog();
        botonOctavos = new javax.swing.JButton();
        botonCuartos = new javax.swing.JButton();
        botonSemis = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        ventanaRegistro = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNomEquipo = new javax.swing.JTextField();
        jTextFieldPais = new javax.swing.JTextField();
        jComboBoxGrupo = new javax.swing.JComboBox<>();
        jComboBoxPosicionEnGrupo = new javax.swing.JComboBox<>();
        jButtonAñadeEquipo = new javax.swing.JButton();
        botonTerminarRegistro = new javax.swing.JButton();
        ventanaConsultaEquiposRegistrados = new javax.swing.JDialog();
        botonSalirVentanaConsultaEquipo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaMostrarEquipos = new javax.swing.JTextArea();
        ventanaEmparejamiento = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        cerrarApp = new javax.swing.JButton();
        muestraEquipo1 = new javax.swing.JTextField();
        vs1 = new javax.swing.JLabel();
        muestraEquipo2 = new javax.swing.JTextField();
        muestraEquipo3 = new javax.swing.JTextField();
        vs2 = new javax.swing.JLabel();
        muestraEquipo4 = new javax.swing.JTextField();
        muestraEquipo5 = new javax.swing.JTextField();
        vs3 = new javax.swing.JLabel();
        muestraEquipo6 = new javax.swing.JTextField();
        muestraEquipo7 = new javax.swing.JTextField();
        vs4 = new javax.swing.JLabel();
        muestraEquipo8 = new javax.swing.JTextField();
        muestraEquipo9 = new javax.swing.JTextField();
        vs5 = new javax.swing.JLabel();
        muestraEquipo10 = new javax.swing.JTextField();
        muestraEquipo11 = new javax.swing.JTextField();
        vs6 = new javax.swing.JLabel();
        muestraEquipo12 = new javax.swing.JTextField();
        muestraEquipo13 = new javax.swing.JTextField();
        vs7 = new javax.swing.JLabel();
        muestraEquipo14 = new javax.swing.JTextField();
        muestraEquipo15 = new javax.swing.JTextField();
        vs8 = new javax.swing.JLabel();
        muestraEquipo16 = new javax.swing.JTextField();
        muestraGIF = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        botonTipoSorteo = new javax.swing.JButton();
        botonRegistrarEquipos = new javax.swing.JButton();
        botonEmparejamiento = new javax.swing.JButton();
        jButtonConsultarEquipos = new javax.swing.JButton();

        botonOctavos.setText("OCTAVOS DE FINAL");
        botonOctavos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOctavosActionPerformed(evt);
            }
        });

        botonCuartos.setText("CUARTOS DE FINAL");
        botonCuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCuartosActionPerformed(evt);
            }
        });

        botonSemis.setText("SEMIFINALES");
        botonSemis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSemisActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TIPO DE SORTEO");

        javax.swing.GroupLayout ventanaTipoSorteoLayout = new javax.swing.GroupLayout(ventanaTipoSorteo.getContentPane());
        ventanaTipoSorteo.getContentPane().setLayout(ventanaTipoSorteoLayout);
        ventanaTipoSorteoLayout.setHorizontalGroup(
            ventanaTipoSorteoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaTipoSorteoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ventanaTipoSorteoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaTipoSorteoLayout.createSequentialGroup()
                        .addComponent(botonOctavos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonSemis)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaTipoSorteoLayout.createSequentialGroup()
                        .addGap(0, 99, Short.MAX_VALUE)
                        .addGroup(ventanaTipoSorteoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaTipoSorteoLayout.createSequentialGroup()
                                .addComponent(botonCuartos)
                                .addGap(137, 137, 137))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaTipoSorteoLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(103, 103, 103))))))
        );
        ventanaTipoSorteoLayout.setVerticalGroup(
            ventanaTipoSorteoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaTipoSorteoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(ventanaTipoSorteoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonOctavos)
                    .addComponent(botonSemis))
                .addGap(31, 31, 31)
                .addComponent(botonCuartos)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOMBRE DEL EQUIPO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PAÍS DEL EQUIPO");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("GRUPO DEL QUE PROCEDE");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("POSICIÓN EN LA QUE CLASIFICÓ");

        jTextFieldNomEquipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldPais.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jComboBoxGrupo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F", "G", "H" }));

        jComboBoxPosicionEnGrupo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxPosicionEnGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));

        jButtonAñadeEquipo.setText("AÑADIR EQUIPO");
        jButtonAñadeEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadeEquipoActionPerformed(evt);
            }
        });

        botonTerminarRegistro.setText("TERMINAR REGISTRO");
        botonTerminarRegistro.setEnabled(false);
        botonTerminarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTerminarRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ventanaRegistroLayout = new javax.swing.GroupLayout(ventanaRegistro.getContentPane());
        ventanaRegistro.getContentPane().setLayout(ventanaRegistroLayout);
        ventanaRegistroLayout.setHorizontalGroup(
            ventanaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaRegistroLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(ventanaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ventanaRegistroLayout.createSequentialGroup()
                        .addComponent(jButtonAñadeEquipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonTerminarRegistro))
                    .addGroup(ventanaRegistroLayout.createSequentialGroup()
                        .addGroup(ventanaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(ventanaRegistroLayout.createSequentialGroup()
                                .addGroup(ventanaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 40, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ventanaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ventanaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldNomEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                .addComponent(jTextFieldPais))))
                    .addGroup(ventanaRegistroLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxPosicionEnGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
        ventanaRegistroLayout.setVerticalGroup(
            ventanaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaRegistroLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(ventanaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNomEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ventanaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaRegistroLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ventanaRegistroLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldPais, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(ventanaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(ventanaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPosicionEnGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 38, Short.MAX_VALUE)
                .addGroup(ventanaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAñadeEquipo)
                    .addComponent(botonTerminarRegistro))
                .addGap(21, 21, 21))
        );

        botonSalirVentanaConsultaEquipo.setText("SALIR");
        botonSalirVentanaConsultaEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirVentanaConsultaEquipoActionPerformed(evt);
            }
        });

        jTextAreaMostrarEquipos.setEditable(false);
        jTextAreaMostrarEquipos.setColumns(20);
        jTextAreaMostrarEquipos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextAreaMostrarEquipos.setRows(5);
        jScrollPane1.setViewportView(jTextAreaMostrarEquipos);

        javax.swing.GroupLayout ventanaConsultaEquiposRegistradosLayout = new javax.swing.GroupLayout(ventanaConsultaEquiposRegistrados.getContentPane());
        ventanaConsultaEquiposRegistrados.getContentPane().setLayout(ventanaConsultaEquiposRegistradosLayout);
        ventanaConsultaEquiposRegistradosLayout.setHorizontalGroup(
            ventanaConsultaEquiposRegistradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaConsultaEquiposRegistradosLayout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonSalirVentanaConsultaEquipo)
                .addGap(20, 20, 20))
        );
        ventanaConsultaEquiposRegistradosLayout.setVerticalGroup(
            ventanaConsultaEquiposRegistradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaConsultaEquiposRegistradosLayout.createSequentialGroup()
                .addGroup(ventanaConsultaEquiposRegistradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaConsultaEquiposRegistradosLayout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(botonSalirVentanaConsultaEquipo))
                    .addGroup(ventanaConsultaEquiposRegistradosLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        ventanaEmparejamiento.setSize(new java.awt.Dimension(425, 592));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("EMPAREJAMIENTOS");

        cerrarApp.setText("SALIR");
        cerrarApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarAppActionPerformed(evt);
            }
        });

        muestraEquipo1.setEditable(false);
        muestraEquipo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        muestraEquipo1.setEnabled(false);

        vs1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        vs1.setText("VS");
        vs1.setEnabled(false);

        muestraEquipo2.setEditable(false);
        muestraEquipo2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        muestraEquipo2.setEnabled(false);

        muestraEquipo3.setEditable(false);
        muestraEquipo3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        muestraEquipo3.setEnabled(false);

        vs2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        vs2.setText("VS");
        vs2.setEnabled(false);

        muestraEquipo4.setEditable(false);
        muestraEquipo4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        muestraEquipo4.setEnabled(false);

        muestraEquipo5.setEditable(false);
        muestraEquipo5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        muestraEquipo5.setEnabled(false);

        vs3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        vs3.setText("VS");
        vs3.setEnabled(false);

        muestraEquipo6.setEditable(false);
        muestraEquipo6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        muestraEquipo6.setEnabled(false);

        muestraEquipo7.setEditable(false);
        muestraEquipo7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        vs4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        vs4.setText("VS");
        vs4.setEnabled(false);

        muestraEquipo8.setEditable(false);
        muestraEquipo8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        muestraEquipo9.setEditable(false);
        muestraEquipo9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        vs5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        vs5.setText("VS");
        vs5.setEnabled(false);

        muestraEquipo10.setEditable(false);
        muestraEquipo10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        muestraEquipo10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muestraEquipo10ActionPerformed(evt);
            }
        });

        muestraEquipo11.setEditable(false);
        muestraEquipo11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        muestraEquipo11.setEnabled(false);
        muestraEquipo11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muestraEquipo11ActionPerformed(evt);
            }
        });

        vs6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        vs6.setText("VS");
        vs6.setEnabled(false);

        muestraEquipo12.setEditable(false);
        muestraEquipo12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        muestraEquipo12.setEnabled(false);

        muestraEquipo13.setEditable(false);
        muestraEquipo13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        muestraEquipo13.setEnabled(false);

        vs7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        vs7.setText("VS");
        vs7.setEnabled(false);

        muestraEquipo14.setEditable(false);
        muestraEquipo14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        muestraEquipo14.setEnabled(false);

        muestraEquipo15.setEditable(false);
        muestraEquipo15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        muestraEquipo15.setEnabled(false);

        vs8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        vs8.setText("VS");
        vs8.setEnabled(false);

        muestraEquipo16.setEditable(false);
        muestraEquipo16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        muestraEquipo16.setEnabled(false);

        javax.swing.GroupLayout ventanaEmparejamientoLayout = new javax.swing.GroupLayout(ventanaEmparejamiento.getContentPane());
        ventanaEmparejamiento.getContentPane().setLayout(ventanaEmparejamientoLayout);
        ventanaEmparejamientoLayout.setHorizontalGroup(
            ventanaEmparejamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaEmparejamientoLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(ventanaEmparejamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ventanaEmparejamientoLayout.createSequentialGroup()
                        .addComponent(muestraEquipo3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vs2)
                        .addGap(18, 18, 18)
                        .addComponent(muestraEquipo4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ventanaEmparejamientoLayout.createSequentialGroup()
                        .addComponent(muestraEquipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vs1)
                        .addGap(18, 18, 18)
                        .addComponent(muestraEquipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ventanaEmparejamientoLayout.createSequentialGroup()
                        .addComponent(muestraEquipo5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vs3)
                        .addGap(18, 18, 18)
                        .addComponent(muestraEquipo6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ventanaEmparejamientoLayout.createSequentialGroup()
                        .addComponent(muestraEquipo7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vs4)
                        .addGap(18, 18, 18)
                        .addComponent(muestraEquipo8, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ventanaEmparejamientoLayout.createSequentialGroup()
                        .addComponent(muestraEquipo9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vs5)
                        .addGap(18, 18, 18)
                        .addComponent(muestraEquipo10, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ventanaEmparejamientoLayout.createSequentialGroup()
                        .addComponent(muestraEquipo11, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vs6)
                        .addGap(18, 18, 18)
                        .addComponent(muestraEquipo12, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ventanaEmparejamientoLayout.createSequentialGroup()
                        .addComponent(muestraEquipo13, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vs7)
                        .addGap(18, 18, 18)
                        .addComponent(muestraEquipo14, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(muestraGIF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ventanaEmparejamientoLayout.createSequentialGroup()
                        .addComponent(muestraEquipo15, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vs8)
                        .addGap(18, 18, 18)
                        .addComponent(muestraEquipo16, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaEmparejamientoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cerrarApp)
                .addGap(33, 33, 33))
        );
        ventanaEmparejamientoLayout.setVerticalGroup(
            ventanaEmparejamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaEmparejamientoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ventanaEmparejamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(muestraEquipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vs1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(muestraEquipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ventanaEmparejamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(muestraEquipo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vs2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(muestraEquipo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ventanaEmparejamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(muestraEquipo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vs3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(muestraEquipo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ventanaEmparejamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(muestraEquipo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vs4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(muestraEquipo8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ventanaEmparejamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(muestraEquipo9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vs5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(muestraEquipo10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ventanaEmparejamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(muestraEquipo11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vs6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(muestraEquipo12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ventanaEmparejamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(muestraEquipo13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vs7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(muestraEquipo14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ventanaEmparejamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(muestraEquipo15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vs8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(muestraEquipo16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(muestraGIF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cerrarApp)
                .addGap(21, 21, 21))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SORTEO CHAMPIONS");

        botonTipoSorteo.setText("TIPO SORTEO");
        botonTipoSorteo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTipoSorteoActionPerformed(evt);
            }
        });

        botonRegistrarEquipos.setText("REGISTRAR EQUIPOS");
        botonRegistrarEquipos.setEnabled(false);
        botonRegistrarEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarEquiposActionPerformed(evt);
            }
        });

        botonEmparejamiento.setText("EMPAREJAMIENTO");
        botonEmparejamiento.setEnabled(false);
        botonEmparejamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEmparejamientoActionPerformed(evt);
            }
        });

        jButtonConsultarEquipos.setText("EQUIPOS REGISTRADOS");
        jButtonConsultarEquipos.setEnabled(false);
        jButtonConsultarEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarEquiposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonConsultarEquipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonEmparejamiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonRegistrarEquipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonTipoSorteo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonTipoSorteo)
                .addGap(34, 34, 34)
                .addComponent(botonRegistrarEquipos)
                .addGap(37, 37, 37)
                .addComponent(botonEmparejamiento)
                .addGap(37, 37, 37)
                .addComponent(jButtonConsultarEquipos)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonTipoSorteoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTipoSorteoActionPerformed
        this.ventanaTipoSorteo.setVisible(true);
        this.ventanaTipoSorteo.setSize(420, 390);
    }//GEN-LAST:event_botonTipoSorteoActionPerformed

    private void botonOctavosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOctavosActionPerformed
        opcion=3;
        
        this.botonTipoSorteo.setEnabled(false);
        this.ventanaTipoSorteo.setVisible(false);
        this.botonRegistrarEquipos.setEnabled(true);
    }//GEN-LAST:event_botonOctavosActionPerformed

    private void botonRegistrarEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarEquiposActionPerformed
        this.ventanaRegistro.setVisible(true);
        this.ventanaRegistro.setSize(420, 390);
    }//GEN-LAST:event_botonRegistrarEquiposActionPerformed

    private void botonSalirVentanaConsultaEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirVentanaConsultaEquipoActionPerformed
        this.ventanaConsultaEquiposRegistrados.setVisible(false);
        this.jButtonConsultarEquipos.setEnabled(false);
        this.botonEmparejamiento.setEnabled(true);
    }//GEN-LAST:event_botonSalirVentanaConsultaEquipoActionPerformed

    private void jButtonAñadeEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadeEquipoActionPerformed
        if(opcion == 3){
            Equipo e=new Equipo(this.jTextFieldNomEquipo.getText(), this.jTextFieldPais.getText(), 
                this.jComboBoxPosicionEnGrupo.getSelectedItem().toString(),
                this.jComboBoxPosicionEnGrupo.getSelectedItem().toString());
            bombo.add(e);
            
            if(bombo.size() == 16){
                this.botonTerminarRegistro.setEnabled(true);
                this.jButtonAñadeEquipo.setEnabled(false);
                
                this.jTextFieldNomEquipo.setEnabled(false);
                this.jTextFieldPais.setEnabled(false);
            }
        }
        
        if(opcion == 2){
            Equipo e=new Equipo(this.jTextFieldNomEquipo.getText(), this.jTextFieldPais.getText());
            bombo.add(e);
            
            if(bombo.size() == 8){
                this.botonTerminarRegistro.setEnabled(true);
                this.jButtonAñadeEquipo.setEnabled(false);
                
                this.jTextFieldNomEquipo.setEnabled(false);
                this.jTextFieldPais.setEnabled(false);
            }
        }
        
        if(opcion == 1){
            Equipo e=new Equipo(this.jTextFieldNomEquipo.getText(), this.jTextFieldPais.getText());
            bombo.add(e);
            
            if(bombo.size() == 4){
                this.botonTerminarRegistro.setEnabled(true);
                this.jButtonAñadeEquipo.setEnabled(false);
                
                this.jTextFieldNomEquipo.setEnabled(false);
                this.jTextFieldPais.setEnabled(false);
            }
        }
      
        this.jTextFieldNomEquipo.setText("");
        this.jTextFieldPais.setText("");
        this.jComboBoxGrupo.setSelectedIndex(0);
        this.jComboBoxPosicionEnGrupo.setSelectedIndex(0);
        
    }//GEN-LAST:event_jButtonAñadeEquipoActionPerformed

    private void botonSemisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSemisActionPerformed
        opcion=1;
        
        this.botonTipoSorteo.setEnabled(false);
        this.ventanaTipoSorteo.setVisible(false);
        this.botonRegistrarEquipos.setEnabled(true);
        this.jComboBoxGrupo.setEnabled(false);
        this.jComboBoxPosicionEnGrupo.setEnabled(false);
    }//GEN-LAST:event_botonSemisActionPerformed

    private void botonCuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCuartosActionPerformed
        opcion=2;
        
        this.botonTipoSorteo.setEnabled(false);
        this.ventanaTipoSorteo.setVisible(false);
        this.botonRegistrarEquipos.setEnabled(true);
        this.jComboBoxGrupo.setEnabled(false);
        this.jComboBoxPosicionEnGrupo.setEnabled(false);
    }//GEN-LAST:event_botonCuartosActionPerformed

    private void botonTerminarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTerminarRegistroActionPerformed
        this.ventanaRegistro.setVisible(false);
        this.jButtonConsultarEquipos.setEnabled(true);
        this.botonRegistrarEquipos.setEnabled(false);
    }//GEN-LAST:event_botonTerminarRegistroActionPerformed

    private void jButtonConsultarEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarEquiposActionPerformed
        this.ventanaConsultaEquiposRegistrados.setVisible(true);
        this.ventanaConsultaEquiposRegistrados.setSize(450,420);
        
        for (int i=0; i<bombo.size();i++) {
            if(i == bombo.size()-1){
                this.jTextAreaMostrarEquipos.append(bombo.get(i).getNombre());
            }else{
                 this.jTextAreaMostrarEquipos.append(bombo.get(i).getNombre()+"\n");
            }
        }
    }//GEN-LAST:event_jButtonConsultarEquiposActionPerformed

    private void botonEmparejamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEmparejamientoActionPerformed
        this.ventanaEmparejamiento.setSize(500,680);
        
        this.ventanaEmparejamiento.setVisible(true);
        
        int equipoNuevo=0;
        int equipoAnterior=0;
        
        Icon imagen=new ImageIcon("C:\\Users\\JAVI\\Documents\\NetBeansProjects\\SorteoUEFA\\src\\main\\java\\gifSorteo.gif");
        this.muestraGIF.setIcon(imagen);
        
        if(opcion == 1){
            this.vs4.setEnabled(true);
            this.vs5.setEnabled(true);
            
            while(!bombo.isEmpty()){
                if(this.muestraEquipo7.getText().contains("")){
                    equipoNuevo=(int) (Math.random() *(4));
                    if(bombo.get(equipoNuevo) != null){
                        this.muestraEquipo7.setText(bombo.get(equipoNuevo).getNombre());
                        bombo.remove(equipoNuevo); 
                    }
                }
                
                if(this.muestraEquipo8.getText().contains("")){
                    equipoNuevo=(int) (Math.random() *(3));
                    if(bombo.get(equipoNuevo) != null){
                        this.muestraEquipo8.setText(bombo.get(equipoNuevo).getNombre());
                        bombo.remove(equipoNuevo); 
                    }
                }

                if(this.muestraEquipo9.getText().contains("")){
                    equipoNuevo=(int) (Math.random() *(2));
                    if(bombo.get(equipoNuevo) != null){
                        this.muestraEquipo9.setText(bombo.get(equipoNuevo).getNombre());
                        bombo.remove(equipoNuevo); 
                    }
                }

                if(this.muestraEquipo10.getText().contains("")){
                    if(bombo.get(0) != null){
                        this.muestraEquipo10.setText(bombo.get(0).getNombre());
                        bombo.remove(0);
                    }
                } 
            }
        }
        
        if(opcion == 2){
            this.muestraEquipo5.setEnabled(true);
            this.muestraEquipo6.setEnabled(true);
            this.muestraEquipo11.setEnabled(true);
            this.muestraEquipo12.setEnabled(true);
            
            this.vs3.setEnabled(true);
            this.vs4.setEnabled(true);
            this.vs5.setEnabled(true);
            this.vs6.setEnabled(true);
            
            while(!bombo.isEmpty()){
                if(this.muestraEquipo5.getText().contains("")){
                    equipoNuevo=(int) (Math.random() *(8));
                    
                    if(bombo.get(equipoNuevo) != null){
                        this.muestraEquipo5.setText(bombo.get(equipoNuevo).getNombre());
                        bombo.remove(equipoNuevo); 
                    }
                }
                
                if(this.muestraEquipo6.getText().contains("")){
                    equipoNuevo=(int) (Math.random() *(7));
                    if(bombo.get(equipoNuevo) != null){
                        this.muestraEquipo6.setText(bombo.get(equipoNuevo).getNombre());
                        bombo.remove(equipoNuevo); 
                    }
                }

                if(this.muestraEquipo7.getText().contains("")){
                    equipoNuevo=(int) (Math.random() *(6));
                    if(bombo.get(equipoNuevo) != null){
                        this.muestraEquipo7.setText(bombo.get(equipoNuevo).getNombre());
                        bombo.remove(equipoNuevo); 
                    }
                }
                
                if(this.muestraEquipo8.getText().contains("")){
                    equipoNuevo=(int) (Math.random() *(5));
                    if(bombo.get(equipoNuevo) != null){
                        this.muestraEquipo8.setText(bombo.get(equipoNuevo).getNombre());
                        bombo.remove(equipoNuevo); 
                    }
                }

                if(this.muestraEquipo9.getText().contains("")){
                    equipoNuevo=(int) (Math.random() *(4));
                    if(bombo.get(equipoNuevo) != null){
                        this.muestraEquipo9.setText(bombo.get(equipoNuevo).getNombre());
                        bombo.remove(equipoNuevo); 
                    }
                }
                
                if(this.muestraEquipo10.getText().contains("")){
                    equipoNuevo=(int) (Math.random() *(3));
                    if(bombo.get(equipoNuevo) != null){
                        this.muestraEquipo10.setText(bombo.get(equipoNuevo).getNombre());
                        bombo.remove(equipoNuevo); 
                    }
                }
                
                if(this.muestraEquipo11.getText().contains("")){
                    equipoNuevo=(int) (Math.random() *(2));
                    if(bombo.get(equipoNuevo) != null){
                        this.muestraEquipo11.setText(bombo.get(equipoNuevo).getNombre());
                        bombo.remove(equipoNuevo); 
                    }
                }         
                
                if(this.muestraEquipo12.getText().contains("")){
                    if(bombo.get(0) != null){
                        this.muestraEquipo12.setText(bombo.get(0).getNombre());
                        bombo.remove(0);
                    }
                } 
            }
        } 
        
        if(opcion == 3){
            this.muestraEquipo1.setEnabled(true);
            this.muestraEquipo2.setEnabled(true);
            this.muestraEquipo3.setEnabled(true);
            this.muestraEquipo4.setEnabled(true);
            this.muestraEquipo5.setEnabled(true);
            this.muestraEquipo6.setEnabled(true);
            this.muestraEquipo7.setEnabled(true);
            this.muestraEquipo8.setEnabled(true);
            this.muestraEquipo9.setEnabled(true);
            this.muestraEquipo10.setEnabled(true);
            this.muestraEquipo11.setEnabled(true);
            this.muestraEquipo12.setEnabled(true);
            this.muestraEquipo13.setEnabled(true);
            this.muestraEquipo14.setEnabled(true);
            this.muestraEquipo15.setEnabled(true);
            this.muestraEquipo16.setEnabled(true);
            
            this.vs1.setEnabled(true);
            this.vs2.setEnabled(true);
            this.vs3.setEnabled(true);
            this.vs4.setEnabled(true);
            this.vs5.setEnabled(true);
            this.vs6.setEnabled(true);
            this.vs7.setEnabled(true);
            this.vs8.setEnabled(true);
            
            boolean seRepite=true;
            
            while(!bombo.isEmpty()){
                if(this.muestraEquipo1.getText().contains("")){
                    equipoNuevo=(int) (Math.random() *(15-0));
                    equipoAnterior=equipoNuevo;
                    this.muestraEquipo1.setText(bombo.get(equipoNuevo).getNombre());
                    bombo.remove(equipoNuevo);
                    
                }    
                
                if(this.muestraEquipo2.getText().contains("")){
                    equipoNuevo=(int) (Math.random() *(14-0));
                    seRepite=bombo.get(equipoAnterior).getPais().contains(bombo.get(equipoNuevo).getPais()) || bombo.get(equipoAnterior).getGrupo().contains(bombo.get(equipoNuevo).getGrupo()) || bombo.get(equipoAnterior).getClasificacion().contains(bombo.get(equipoNuevo).getClasificacion());
                    
                    for(int k=0; seRepite = false; k++){
                        equipoNuevo=(int) (Math.random() *(14-0));
                    }    
                    
                    this.muestraEquipo2.setText(bombo.get(equipoNuevo).getNombre());
                    bombo.remove(equipoNuevo);
                    
                }

                if(this.muestraEquipo3.getText().contains("")){
                    equipoNuevo=(int) (Math.random() *(13-0));
                    equipoAnterior=equipoNuevo;
                    this.muestraEquipo3.setText(bombo.get(equipoNuevo).getNombre());
                    bombo.remove(equipoNuevo);
                    
                }
                
                if(this.muestraEquipo4.getText().contains("")){
                    equipoNuevo=(int) (Math.random() *(12-0));
                    seRepite=bombo.get(equipoAnterior).getPais().contains(bombo.get(equipoNuevo).getPais()) || bombo.get(equipoAnterior).getGrupo().contains(bombo.get(equipoNuevo).getGrupo()) || bombo.get(equipoAnterior).getClasificacion().contains(bombo.get(equipoNuevo).getClasificacion());
                    
                    for(int k=0; seRepite = false; k++){
                        equipoNuevo=(int) (Math.random() *(12-0));
                    }    
                    
                    this.muestraEquipo4.setText(bombo.get(equipoNuevo).getNombre());
                    bombo.remove(equipoNuevo);
                }
                
                if(this.muestraEquipo5.getText().contains("")){
                    equipoNuevo=(int) (Math.random() *(11-0));
                    equipoAnterior=equipoNuevo;
                    this.muestraEquipo5.setText(bombo.get(equipoNuevo).getNombre());
                    bombo.remove(equipoNuevo);   
                }    
                
                if(this.muestraEquipo6.getText().contains("")){
                    equipoNuevo=(int) (Math.random() *(10-0));
                    seRepite=bombo.get(equipoAnterior).getPais().contains(bombo.get(equipoNuevo).getPais()) || bombo.get(equipoAnterior).getGrupo().contains(bombo.get(equipoNuevo).getGrupo()) || bombo.get(equipoAnterior).getClasificacion().contains(bombo.get(equipoNuevo).getClasificacion());
                    
                    for(int k=0; seRepite = false; k++){
                        equipoNuevo=(int) (Math.random() *(10-0));
                    }    
                    
                    this.muestraEquipo6.setText(bombo.get(equipoNuevo).getNombre());
                    bombo.remove(equipoNuevo);
                }

                if(this.muestraEquipo7.getText().contains("")){
                    equipoNuevo=(int) (Math.random() *(9-0));
                    equipoAnterior=equipoNuevo;
                    this.muestraEquipo7.setText(bombo.get(equipoNuevo).getNombre());
                    bombo.remove(equipoNuevo);
                }
                
                if(this.muestraEquipo8.getText().contains("")){
                    equipoNuevo=(int) (Math.random() *(8-0));
                    seRepite=bombo.get(equipoAnterior).getPais().contains(bombo.get(equipoNuevo).getPais()) || bombo.get(equipoAnterior).getGrupo().contains(bombo.get(equipoNuevo).getGrupo()) || bombo.get(equipoAnterior).getClasificacion().contains(bombo.get(equipoNuevo).getClasificacion());
                    
                    for(int k=0; seRepite = false; k++){
                        equipoNuevo=(int) (Math.random() *(8-0));
                    }    
                    
                    this.muestraEquipo8.setText(bombo.get(equipoNuevo).getNombre());
                    bombo.remove(equipoNuevo);
                }
                
                if(this.muestraEquipo9.getText().contains("")){
                    equipoNuevo=(int) (Math.random() *(7-0));
                    equipoAnterior=equipoNuevo;
                    this.muestraEquipo9.setText(bombo.get(equipoNuevo).getNombre());
                    bombo.remove(equipoNuevo);
                    
                }    
                
                if(this.muestraEquipo10.getText().contains("")){
                    equipoNuevo=(int) (Math.random() *(6-0));
                    seRepite=bombo.get(equipoAnterior).getPais().contains(bombo.get(equipoNuevo).getPais()) || bombo.get(equipoAnterior).getGrupo().contains(bombo.get(equipoNuevo).getGrupo()) || bombo.get(equipoAnterior).getClasificacion().contains(bombo.get(equipoNuevo).getClasificacion());
                    
                    for(int k=0; seRepite = false; k++){
                        equipoNuevo=(int) (Math.random() *(6-0));
                    }    
                    
                    this.muestraEquipo10.setText(bombo.get(equipoNuevo).getNombre());
                    bombo.remove(equipoNuevo);
                }

                if(this.muestraEquipo11.getText().contains("")){
                    equipoNuevo=(int) (Math.random() *(5-0));
                    equipoAnterior=equipoNuevo;
                    this.muestraEquipo11.setText(bombo.get(equipoNuevo).getNombre());
                    bombo.remove(equipoNuevo);  
                }
                
                if(this.muestraEquipo12.getText().contains("")){
                    equipoNuevo=(int) (Math.random() *(4-0));
                    seRepite=bombo.get(equipoAnterior).getPais().contains(bombo.get(equipoNuevo).getPais()) || bombo.get(equipoAnterior).getGrupo().contains(bombo.get(equipoNuevo).getGrupo()) || bombo.get(equipoAnterior).getClasificacion().contains(bombo.get(equipoNuevo).getClasificacion());
                    
                    for(int k=0; seRepite = false; k++){
                        equipoNuevo=(int) (Math.random() *(4-0));
                    }    
                    
                    this.muestraEquipo12.setText(bombo.get(equipoNuevo).getNombre());
                    bombo.remove(equipoNuevo);
                }
                
                if(this.muestraEquipo13.getText().contains("")){
                    equipoNuevo=(int) (Math.random() *(3-0));
                    equipoAnterior=equipoNuevo;
                    this.muestraEquipo13.setText(bombo.get(equipoNuevo).getNombre());
                    bombo.remove(equipoNuevo); 
                }    
                
                if(this.muestraEquipo14.getText().contains("")){
                    equipoNuevo=(int) (Math.random() *(2-0));
                    seRepite=bombo.get(equipoAnterior).getPais().contains(bombo.get(equipoNuevo).getPais()) || bombo.get(equipoAnterior).getGrupo().contains(bombo.get(equipoNuevo).getGrupo()) || bombo.get(equipoAnterior).getClasificacion().contains(bombo.get(equipoNuevo).getClasificacion());
                    
                    for(int k=0; seRepite = false; k++){
                        equipoNuevo=(int) (Math.random() *(2-0));
                    }    
                    
                    this.muestraEquipo14.setText(bombo.get(equipoNuevo).getNombre());
                    bombo.remove(equipoNuevo);
               }

                if(this.muestraEquipo15.getText().contains("")){
                    equipoNuevo=(int) (Math.random() *(1-0));
                    equipoAnterior=equipoNuevo;
                    this.muestraEquipo15.setText(bombo.get(equipoNuevo).getNombre());
                    bombo.remove(equipoNuevo);
                }
                
                if(this.muestraEquipo16.getText().contains("")){
                    this.muestraEquipo16.setText(bombo.get(0).getNombre());
                    bombo.remove(0); 
                }    
            }
        } 
    }//GEN-LAST:event_botonEmparejamientoActionPerformed

    private void cerrarAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarAppActionPerformed
        this.ventanaEmparejamiento.setVisible(false);
        this.setVisible(false);
    }//GEN-LAST:event_cerrarAppActionPerformed

    private void muestraEquipo10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muestraEquipo10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_muestraEquipo10ActionPerformed

    private void muestraEquipo11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muestraEquipo11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_muestraEquipo11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EJ2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EJ2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EJ2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EJ2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EJ2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCuartos;
    private javax.swing.JButton botonEmparejamiento;
    private javax.swing.JButton botonOctavos;
    private javax.swing.JButton botonRegistrarEquipos;
    private javax.swing.JButton botonSalirVentanaConsultaEquipo;
    private javax.swing.JButton botonSemis;
    private javax.swing.JButton botonTerminarRegistro;
    private javax.swing.JButton botonTipoSorteo;
    private javax.swing.JButton cerrarApp;
    private javax.swing.JButton jButtonAñadeEquipo;
    private javax.swing.JButton jButtonConsultarEquipos;
    private javax.swing.JComboBox<String> jComboBoxGrupo;
    private javax.swing.JComboBox<String> jComboBoxPosicionEnGrupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaMostrarEquipos;
    private javax.swing.JTextField jTextFieldNomEquipo;
    private javax.swing.JTextField jTextFieldPais;
    private javax.swing.JTextField muestraEquipo1;
    private javax.swing.JTextField muestraEquipo10;
    private javax.swing.JTextField muestraEquipo11;
    private javax.swing.JTextField muestraEquipo12;
    private javax.swing.JTextField muestraEquipo13;
    private javax.swing.JTextField muestraEquipo14;
    private javax.swing.JTextField muestraEquipo15;
    private javax.swing.JTextField muestraEquipo16;
    private javax.swing.JTextField muestraEquipo2;
    private javax.swing.JTextField muestraEquipo3;
    private javax.swing.JTextField muestraEquipo4;
    private javax.swing.JTextField muestraEquipo5;
    private javax.swing.JTextField muestraEquipo6;
    private javax.swing.JTextField muestraEquipo7;
    private javax.swing.JTextField muestraEquipo8;
    private javax.swing.JTextField muestraEquipo9;
    private javax.swing.JLabel muestraGIF;
    private javax.swing.JDialog ventanaConsultaEquiposRegistrados;
    private javax.swing.JDialog ventanaEmparejamiento;
    private javax.swing.JDialog ventanaRegistro;
    private javax.swing.JDialog ventanaTipoSorteo;
    private javax.swing.JLabel vs1;
    private javax.swing.JLabel vs2;
    private javax.swing.JLabel vs3;
    private javax.swing.JLabel vs4;
    private javax.swing.JLabel vs5;
    private javax.swing.JLabel vs6;
    private javax.swing.JLabel vs7;
    private javax.swing.JLabel vs8;
    // End of variables declaration//GEN-END:variables
}
